name: Main

on:
  pull_request:
    branches: [master]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - name: npm install
        run: npm install
      - name: npm run lint
        run: npm run lint
      - name: npm test
        run: npm test
